language: node_js
node_js:
- "5.7"
- "0.12"
- "iojs"
services:
- postgresql
install:
- npm install
before_script:
- npm run lint
- psql -c 'create database block-and-frame-test;' -U postgres
- cp database.yml.travis config/database.yml