sudo: required
language: node_js
node_js:
- "5"
env:
- DB_URL=127.0.0.1 DB_USER= DB_PASSWORD= DB_NAME=block_and_frame_test SECRET=youwillnevergetthis AWS_ACCESS_KEY=idontknowthis AWS_SECRET_KEY=idontknowthis S3_BUCKET=idontknowthis
services:
- postgresql
install:
- npm install
before_script:
- npm run lint
- psql -c 'create database block_and_frame_test;' -U postgres
- cp database.yml.travis server/config/database.yml