sudo: required
language: node_js
node_js:
- "0.12"
services:
- postgresql
install:
- npm install
before_script:
- npm run lint
- psql -c 'create database block_and_frame_test;' -U postgres
- cp database.yml.travis server/config/database.yml